import type { Metadata } from "next";
import NavBar from "./components/app/NavBar";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import Providers from "./components/app/Providers";

export const metadata: Metadata = {
  title: "Thrills World - Your thrills. One app.",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr" suppressHydrationWarning>
      <Providers>
        <body>
          <NavBar></NavBar>
          {children}
        </body>
      </Providers>
    </html>
  );
}
